package com.mcdonalds.ordermachine.model.product;

import jakarta.persistence.Column;
import jakarta.persistence.Enumerated;
import jakarta.persistence.EnumType;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.util.Objects;


@Entity
@Table(name = "ordered_products")
public class Product {
    @Id
    @GeneratedValue
    private Long id;

    @Column(name = "receipt_code", nullable = false)
    private String receiptCode;

    @Column(name = "name", nullable = false)
    private String name;

    @Column(name = "price", nullable = false)
    private Double price;

    @Enumerated(EnumType.STRING)
    @Column(name = "type", nullable = false)
    private ProductType type;


    public Product(Long id, String receiptCode, String name, Double price, ProductType type) {
        this.id = id;
        this.receiptCode = receiptCode;
        this.name = name;
        this.price = price;
        this.type = type;
    }

    public Product() {

    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getReceiptCode() {
        return receiptCode;
    }

    public void setReceiptCode(String receiptCode) {
        this.receiptCode = receiptCode;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public ProductType getType() {
        return type;
    }

    public void setType(ProductType type) {
        this.type = type;
    }


    @Override //autogenerated by Intellij.
    public String toString() {
        return "Product{" +
                "id=" + this.id +
                ", receiptCode='" + this.receiptCode + '\'' +
                ", name='" + this.name + '\'' +
                ", price=" + this.price +
                ", type=" + this.type +
                '}';
    }

    @Override //autogenerated by Intellij.
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Product product = (Product) o;
        return Objects.equals(this.id, product.id) && Objects.equals(this.receiptCode, product.receiptCode) && Objects.equals(this.name, product.name) && Objects.equals(this.price, product.price) && this.type == product.type;
    }

    @Override //autogenerated by Intellij.
    public int hashCode() {
        return Objects.hash(this.id, this.receiptCode, this.name, this.price, this.type);
    }
}

/*  YOU CAN USE RECORD INSTEAD OF THE CLASS WITH ANNOTATIONS!
    public record Product(Long id, String receiptCode, String name, Double price, ProductType type) {

    }
 */